

```{r}
library(tidyverse)
library(ggplot2)
```


```{r}
spp <- combined_pred %>% filter(sp_code == "pcgl")

spp_sum <- combined_pred %>% 
  filter(sp_code == "pcgl") %>% 
  group_by(sens_level) %>% 
  summarise(max = round(max(drought_sens), 3),
            min = round(min(drought_sens), 3)) %>% 
  mutate(diff = round(max - min, 3))


```

```{r}
ggplot(spp_sum) +
  geom_segment(aes(x = min, xend = max, y = 1, col = sens_level), linewidth = 25) +
  scale_color_manual(values = c("High Sensitivity" = "#B03B12",
                                "Moderate Sensitivity" = "#EC9971",
                                "Low Sensitivity" = "#F9E0D2",
                                "Least Concern" = "#144D6F")) +
  geom_text(aes(x = min, y = 1, label = min), vjust = 4, size = 4) +
  geom_text(aes(x = max(max), y = 1, label = max(max)), vjust = 4, size = 4)

```

```{r}
spp <- combined_pred %>% filter(sp_code == "pcgl")

avg <- round(mean(spp$drought_sens), 3)

spp_sum <- combined_pred %>% 
  filter(sp_code == "pcgl") %>% 
  group_by(sens_level) %>% 
  summarise(max = round(max(drought_sens), 3),
            min = round(min(drought_sens), 3)) %>% 
  ungroup() %>% 
  pivot_longer(cols = c(max, min), names_to = "stat", values_to = "value") %>% 
  distinct(value) %>% 
  arrange(value)
  

ggplot() + 
  
  
  geom_segment(aes(x = spp_sum[2,1], xend = spp_sum[1,1], y = 1), col = "#B03B12", linewidth = 25) 

+
  geom_segment(aes(x = spp_sum[2,1], xend = spp_sum[3,1], y = 1), col = "#EC9971", linewidth = 25) +
  geom_segment(aes(x = spp_sum[3,1], xend = spp_sum[4,1], y = 1), col = "#F9E0D2", linewidth = 25) +
  geom_segment(aes(x = spp_sum[4,1], xend = spp_sum[5,1], y = 1), col = "#144D6F", linewidth = 25)


  
  # add minimum values as label
  geom_text(aes(x = 1, y = 1, label = spp_sum[1,1]), vjust = 8) +
  geom_text(aes(x = 2, y = 1, label = spp_sum[2,1]), vjust = 8) +
  geom_text(aes(x = 3, y = 1, label = spp_sum[3,1]), vjust = 8) +
  geom_text(aes(x = 4, y = 1, label = spp_sum[4,1]), vjust = 8) +
  geom_text(aes(x = 5, y = 1, label = spp_sum[5,1]), vjust = 8)


```



